#!/usr/bin/bash
background='#0c0a1e'
foreground='#c2c1c6'
cursor='#c2c1c6'

# Colors
color0='#0c0a1e'
color1='#ae2455'
color2='#3f196c'
color3='#441a6c'
color4='#1b3f85'
color5='#78227d'
color6='#9f1f71'
color7='#908f99'
color8='#5e5b6f'
color9='#E83072'
color10='#542290'
color11='#5B2391'
color12='#2555B2'
color13='#A02EA7'
color14='#D52A97'
color15='#c2c1c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
swaylock \
--screenshots \
--indicator \
--clock \
--font 'CartographCF Nerd Font:style=Thin,Regular 40' \
--inside-wrong-color "$color2"  \
--ring-wrong-color "$color5" \
--inside-clear-color "$background" \
--ring-clear-color "$color2" \
--inside-ver-color "$color3" \
--ring-ver-color "$color3" \
--text-color  "$foreground" \
--indicator-radius 80 \
--indicator-thickness 5 \
--effect-blur 10x20 \
--effect-vignette 0.2:0.2 \
--ring-color "$background" \
--key-hl-color "$color5" \
--bs-hl-color "$color2" \
--line-color "$color5" \
--inside-color "$background" \
--separator-color "$color2" \
--fade-in 0.5 &
